# Generated by Django 6.0.4 on 2026-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('lab', 'Laboratory'), ('seminar', 'Seminar Room')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_index', models.PositiveIntegerField(help_text='Order of the slot in the day (e.g., 1 for morning)')),
            ],
            options={
                'ordering': ['day', 'slot_index'],
                'unique_together': {('day', 'slot_index')},
            },
        ),
    ]
